"""God mode: interventions + direct stat/relation/peace edits. PROPOSAL §3.5, §4.7, §12.3.4.

Interventions are ordinary EventSpecs (`is_intervention=True`) already in EVENT_REGISTRY
(engine/kinds/interventions.py, registered by M3.1); `intervene()` is the thin invocation
path that fires them as root events -- no per-kind functions, no hardcoded kind lists
(r4's raw-injection tier reuses this exact path, §12.3.4). The god-mode palette (M6
bridge) is generated by filtering EVENT_REGISTRY on is_intervention, never enumerated here.

Structural interventions share the organic kinds' handlers (registered in
systems/politics.py): INTERVENE_WAR declares a real war (at_war_with on both sides, relation
-90), INTERVENE_PEACE ends every war of its target, INTERVENE_ALLIANCE forms or joins a bloc
(relation +70), INTERVENE_EMBARGO blocks the trade lane. They inherit the organic guards: a
war fizzles if either side is not ACTIVE, and an alliance between members of two different
blocs only sets the relation because bloc merging is deferred. An alliance does not end a
war already running between the pair. Replay uses the same payload-driven handlers, so
scrubbing and forking reconstruct god-mode outcomes exactly. INTERVENE_SECEDE creates a real
country (systems/secession.py); the asset-class interventions (blockade, blackout, grid
failure, satellite loss, repair) mutate the class they name (systems/infrastructure.py).

Direct edits (god_edit/god_relation/god_peace, §3.5) mutate world state in place WITHOUT
forking (forking itself is the caller's job via Multiverse.fork, M5.2 -- this module never
forks). Each records a synthetic root event carrying before/after values UNLESS
world.settings.silent_god_edits is set, in which case the mutation happens with NO event
at all -- §3.5's literal "paper trail disabled" mode. This is a deliberate, narrow
exception to §4.5's "every mutation needs an owning Event" rule: a silent edit is
invisible to world_at's replay (scrubbing/forking past a silent edit reconstructs the
PRE-edit value), which is the whole point of a mode whose own UI badge warns "paper trail
disabled" -- see docs/design-decisions.md ("M5.1 god mode").
"""

from __future__ import annotations

from meddler.engine import cascade, config, structural
from meddler.engine.events import Event, LedgerEntry, StatDelta
from meddler.engine.ledger import Ledger, apply_to_world, round_money
from meddler.engine.model import Country, World
from meddler.engine.registry import EVENT_REGISTRY, WORLD_RULE_GATES, world_rule_allows
from meddler.engine.rng import Rng
from meddler.engine.stats import apply_country_stat, apply_relation_delta


class InterventionError(ValueError):
    """Raised when god mode is asked for something it cannot or must not do."""


def intervene(
    world: World,
    rng: Rng,
    *,
    kind: str,
    country: str,
    country2: str | None = None,
) -> Event:
    """Fire a registered intervention as a root event (parent_id=None, depth=0,
    is_intervention=True) via the shared cascade path -- applies its stat_deltas/
    pool_transfers and schedules its consequences exactly like any other event (§4.7).

    Raises InterventionError if: god mode is disabled (observer_only), `kind` isn't a
    registered intervention, a target is in protected_countries, or a two-target kind is
    missing its second target.

    INTERVENE_CHAOS resolves to a random registered EXOGENOUS spec, fired as a root event
    in `country`'s place, still flagged is_intervention=True (documented at registration
    time, engine/kinds/interventions.py)."""
    if world.settings.observer_only:
        raise InterventionError("observer_only: god mode is disabled")

    spec = EVENT_REGISTRY.get(kind)
    if spec is None or not spec.is_intervention:
        raise InterventionError(f"not a registered intervention: {kind}")

    for code in (country, country2):
        if code is not None and code in world.settings.protected_countries:
            raise InterventionError(f"{code} is protected from intervention targeting")

    if not world_rule_allows(kind, world.settings):
        rule = WORLD_RULE_GATES[kind]
        raise InterventionError(f"{rule} is off: {kind} is disabled by a world rule")

    if kind == "INTERVENE_CHAOS":
        exogenous_kinds = sorted(k for k, s in EVENT_REGISTRY.items() if s.is_exogenous)
        if not exogenous_kinds:
            raise InterventionError("no exogenous kind registered to resolve chaos into")
        resolved_kind = rng.choice(exogenous_kinds)
        return cascade.emit_event(
            world,
            rng,
            kind=resolved_kind,
            primary=country,
            secondary=None,
            parent_id=None,
            depth=0,
            is_intervention=True,
            payload={"chaos_resolved_to": resolved_kind},
        )

    if spec.targets == 2 and country2 is None:
        raise InterventionError(f"{kind} requires a second target country")

    return cascade.emit_event(
        world,
        rng,
        kind=kind,
        primary=country,
        secondary=country2 if spec.targets == 2 else None,
        parent_id=None,
        depth=0,
        is_intervention=True,
        payload={},
    )


# Engine-native Country attribute names (or "treasury" for the pool). Translating a
# UI-facing name (contract's "grainDays"/"pop"/"gdp") into this is the M6 bridge's job,
# not this module's (§4.1: engine doesn't know about display units).
_EDITABLE_FIELDS = frozenset(
    {"stability", "inflation", "gdp_tick", "population", "treasury", "grain_stock", "exchange_rate"}
)


def god_edit(world: World, code: str, field: str, value: float) -> Event | None:
    """§3.5: godEdit. Directly sets one of _EDITABLE_FIELDS on `code`, recording
    before/after on a synthetic GOD_EDIT root event -- unless silent_god_edits is set
    (see module docstring)."""
    if field not in _EDITABLE_FIELDS:
        raise InterventionError(f"not an editable field: {field}")
    country = world.country(code)
    silent = world.settings.silent_god_edits

    if field == "treasury":
        before = float(country.pools.get("treasury", 0))
        after_int = round_money(value)
        if silent:
            country.pools["treasury"] = after_int
            return None
        ledger: list[LedgerEntry] = []
        delta_amount = after_int - int(before)
        if delta_amount > 0:
            Ledger.mint(ledger, f"{code}.treasury", delta_amount, code)
        elif delta_amount < 0:
            Ledger.burn(ledger, f"{code}.treasury", -delta_amount, code)
        event = world.log.append(
            tick=world.tick,
            kind="GOD_EDIT",
            country=code,
            country2=None,
            parent_id=None,
            depth=0,
            is_intervention=True,
            payload={"field": field, "before": before, "after": float(after_int)},
            ledger=tuple(ledger),
            severity=1,
        )
        for entry in event.ledger:
            apply_to_world(world, entry)
        return event

    before = float(getattr(country, field))
    if silent:
        setattr(country, field, value)
        _shift_temperament(world, None, country, field, value - before)
        return None
    stat_deltas: list[StatDelta] = []
    apply_country_stat(world, stat_deltas, code, field, value - before)
    _shift_temperament(world, stat_deltas, country, field, value - before)
    return world.log.append(
        tick=world.tick,
        kind="GOD_EDIT",
        country=code,
        country2=None,
        parent_id=None,
        depth=0,
        is_intervention=True,
        payload={"field": field, "before": before, "after": value},
        stat_deltas=tuple(stat_deltas),
        severity=1,
    )


def _shift_temperament(
    world: World, stat_deltas: list[StatDelta] | None, country: Country, field: str, delta: float
) -> None:
    """Carry part of a stability edit into the country's equilibrium (§3.5 + M17).

    Stability reverts toward `base_stability` (systems/stability.py), so an edit that moved
    only the current value would visibly drain back to the genesis draw inside a couple of
    hundred ticks -- the most-used god lever would also be the most obviously temporary one.
    Moving the target too makes the edit change where the nation settles.

    The shift rides a StatDelta like every other stat mutation, which is what keeps it
    replay-exact: `stats.replay_stat_delta` ends in a generic setattr, so `world_at` and any
    fork taken off a reconstruction rebuild the moved target through the machinery that
    already exists, with no payload and no handler. base_stability is Country state no event
    would otherwise record, and an unrecorded mutation is exactly the class of bug M8.3
    closed for the consequence queue and the hysteresis arms.
    """
    if field != "stability" or delta == 0.0:
        return
    shift = delta * config.GOD_EDIT_TEMPERAMENT_SHARE
    target = max(0.0, min(100.0, country.base_stability + shift))
    if stat_deltas is None:  # silent mode: apply, record nothing (see module docstring)
        country.base_stability = target
        return
    apply_country_stat(world, stat_deltas, country.code, "base_stability", target - country.base_stability)


def god_relation(world: World, code_a: str, code_b: str, value: float) -> Event | None:
    """§3.5: godRelation. Sets the pair's relation, clamped to [-100, 100]. "Raising a
    relation above -30 auto-ends a war" -- clears at_war_with on both sides if present.
    The relation change rides a StatDelta; the war-ending is recorded as
    `payload["ended_war"]` and rebuilt by `_replay_god_relation`, so world_at does not
    resurrect a war this edit ended. Silent mode (see module docstring) skips the
    event/StatDelta record but still applies the relation change and the war-clearing."""
    a_code, b_code = sorted((code_a, code_b))
    key = (a_code, b_code)
    before = world.relations.get(key, 0.0)
    value = max(-100.0, min(100.0, value))
    silent = world.settings.silent_god_edits

    stat_deltas: list[StatDelta] = []
    if silent:
        world.relations[key] = value
    else:
        apply_relation_delta(world, stat_deltas, code_a, code_b, value - before)

    ended_war = False
    if value > -30.0 and before <= -30.0:
        a, b = world.country(code_a), world.country(code_b)
        if code_b in a.at_war_with:
            a.at_war_with.remove(code_b)
            ended_war = True
        if code_a in b.at_war_with:
            b.at_war_with.remove(code_a)
            ended_war = True

    if silent:
        return None
    return world.log.append(
        tick=world.tick,
        kind="GOD_RELATION_SHIFT",
        country=code_a,
        country2=code_b,
        parent_id=None,
        depth=0,
        is_intervention=True,
        payload={"before": before, "after": value, "ended_war": ended_war},
        stat_deltas=tuple(stat_deltas),
        severity=1,
    )


def _replay_god_relation(world: World, event: Event) -> None:
    """RNG-free replay of god_relation's war-ending (the relation itself is a StatDelta)."""
    if not event.payload.get("ended_war") or event.country is None or event.country2 is None:
        return
    a, b = world.country(event.country), world.country(event.country2)
    if b.code in a.at_war_with:
        a.at_war_with.remove(b.code)
    if a.code in b.at_war_with:
        b.at_war_with.remove(a.code)


structural.register_replay("GOD_RELATION_SHIFT", _replay_god_relation)


def god_peace(world: World, rng: Rng, code: str) -> Event | None:
    """§3.5: godPeace. Fires the real catalog PEACE kind (is_intervention=True) via the
    shared cascade path, which (M7.3) runs a structural handler that clears `code`'s
    at_war_with on both sides and records who it was at war with -- the same generic
    handler that now fires for ANY PEACE event, organic or god-mode (see
    systems/politics.py's _make_peace). silent_god_edits skips the event (and thus the
    generic handler) entirely, so the war-clearing is duplicated here ONLY for that
    branch -- the "paper trail disabled" exception, module docstring; PEACE's own stat
    bump is tied to firing the event, so silent mode skips it too, not just the record."""
    if world.settings.silent_god_edits:
        country = world.country(code)
        for foe_code in list(country.at_war_with):
            foe = world.country(foe_code)
            if code in foe.at_war_with:
                foe.at_war_with.remove(code)
        country.at_war_with = []
        return None
    return cascade.emit_event(
        world,
        rng,
        kind="PEACE",
        primary=code,
        secondary=None,
        parent_id=None,
        depth=0,
        is_intervention=True,
        payload={},
    )
